
export const pagesUnderTest = [
  { name: 'home', path: '/', hasLeadspaceVideo: false },
  { name: 'upcoming-events', path: '/upcoming-events/', hasLeadspaceVideo: false },
  { name: '2016-acla', path: '/2016-acla/', hasLeadspaceVideo: false },
  { name: 'the-latest', path: '/the-latest/', hasLeadspaceVideo: false },
  { name: 'civic-engagement', path: '/civic-engagement/', hasLeadspaceVideo: false },
  { name: 'public-policy', path: '/public-policy/', hasLeadspaceVideo: false },
  { name: 'philanthropy', path: '/philanthropy/', hasLeadspaceVideo: false },
  { name: 'our-blog', path: '/our-blog/', hasLeadspaceVideo: false },
  { name: 'media-center', path: '/media-center/', hasLeadspaceVideo: false },
  { name: 'research', path: '/research/', hasLeadspaceVideo: false },
  { name: 'resources', path: '/resources/', hasLeadspaceVideo: false },
  { name: 'faq', path: '/faq/', hasLeadspaceVideo: false },
  { name: 'additional-programs', path: '/additional-programs/', hasLeadspaceVideo: false },
  { name: 'contact-us', path: '/contact-us/', hasLeadspaceVideo: false },
  { name: 'partners-landing', path: '/partners-landing/', hasLeadspaceVideo: false },
  { name: 'arts-culture', path: '/arts-culture/', hasLeadspaceVideo: false },
  { name: 'next-generation-leaders-impact-projects', path: '/next-generation-leaders-impact-projects/', hasLeadspaceVideo: false },
  { name: 'gala-landing', path: '/gala-landing/', hasLeadspaceVideo: false },
  { name: 'newsletter', path: '/newsletter/', hasLeadspaceVideo: false },
  { name: 'our-board-staff', path: '/our-board-staff/', hasLeadspaceVideo: false },
  { name: 'members-landing', path: '/members-landing/', hasLeadspaceVideo: false },
  { name: 'support-us', path: '/support-us/', hasLeadspaceVideo: false },
  { name: 'research-v2', path: '/research-v2/', hasLeadspaceVideo: false },
  { name: 'members-directory', path: '/members-directory/', hasLeadspaceVideo: false },
  { name: 'about-us', path: '/about-us/', hasLeadspaceVideo: false },
  { name: 'home-page-v2026', path: '/home-page-v2026/', hasLeadspaceVideo: false },
  { name: 'research-and-insights', path: '/research-and-insights/', hasLeadspaceVideo: false },
  { name: 'events-v2026', path: '/events-v2026/', hasLeadspaceVideo: false },
  { name: 'events', path: '/events/', hasLeadspaceVideo: false },
];